apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      initContainers:
      - name: check-db-ready
        image: mysql:5.7
        command: ['sh', '-c', 
          'until mysql -h mysql -u$MYSQL_USER -p$MYSQL_PASSWORD -e "SELECT 1"; do echo waiting for mysql; sleep 2; done']
        env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
      containers:
      - name: flask-app
        image: your-flask-app-image  # Replace with your image
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_HOST
          value: "mysql.app.svc.cluster.local"  # Fully qualified service name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DB
          value: "mydb"
